# Generated by Django 4.1.3 on 2022-11-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='valor',
            field=models.FloatField(),
        ),
    ]
